### ISSUE TITLE
Using PouchDB plugin Store.PouchDB

### ISSUE THREAD

**Issue by heikoholland** [nolanlawson/pouchdb-ionic-2-typescript-demo#4]
Hi,

I'm using Ionic2 RC3 and I can't get the Store.PouchDB plugin (https://github.com/chunksnbits/store.pouchdb) to work.

I cloned this repo and added the plugin to the project via `npm install store.pouchdb --save`. After that I edited the `src/app/app.compnent.ts` to

```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { TabsPage } from '../pages/tabs/tabs';

import PouchDB from 'pouchdb';
import * as PouchDBStore from 'store.pouchdb';


@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage = TabsPage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();

      console.log(PouchDB);
      console.log(PouchDBStore);
    });
  }
}
```

I get the following error:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (http://localhost:8100/build/main.js:82666:45)
    at http://localhost:8100/build/main.js:117055:9
    at createCommonjsModule (http://localhost:8100/build/main.js:6360:35)
    at http://localhost:8100/build/main.js:116896:15
    at http://localhost:8100/build/main.js:140164:2
```

**Comment by nolanlawson** [comment]
I’m not sure what’s going on here. It looks like a bug in the build script, though (main.js).

**Comment by heikoholland** [comment]
I tried some things and ended up installing the latest ionic scripts (`npm install --save-dev @ionic/app-scripts@0.0.46`). The error message changed.

```
Uncaught TypeError: Cannot set property '_name' of undefined                          store.js:26
```

`this` is undefined in this function and I don't know why. I'm not familiar enough with webpack so I don't know why this function is even called at this time because it's called before the app is loaded.

**Comment by nolanlawson** [comment]
This looks like it may be a bug in https://github.com/chunksnbits/store.pouchdb : https://github.com/chunksnbits/store.pouchdb/search?utf8=%E2%9C%93&q=_name

**Comment by heikoholland** [comment]
I think I found the problem.

The `store-loader.js` (https://github.com/chunksnbits/store.pouchdb/blob/master/lib/store-loader.js) requires `pouchdb` to use `.plugin`. In the old ionic version it loads the file in `store.pouchdb/node_modules/pouchdb/`. I'm not sure why this happens but it results in using the `.plugin` method of different classes of PouchDB.

`store.pouchdb` needs the `.plugin` method from `pouch/lib/setup.js/` cause it doesn't execute the given function.

Anyway. I forked it here: https://github.com/heikoholland/store.pouchdb (with another bugfix in `store.js`).
